### ISSUE TITLE
How to use access token and refresh access token automatically

### ISSUE THREAD

**Issue by gayashanbc** [asgardio/asgardio-js-oidc-sdk#17]
**Description:**
There are no examples about how to use the access token in a API request and how the refresh token works?

**Suggested Labels:**
documentation, help

**Comment by thivi** [comment]
Getting access token: https://github.com/asgardio/asgardio-js-oidc-sdk/tree/master/packages/oidc-js#getaccesstoken

The token can be refreshed using this: https://github.com/asgardio/asgardio-js-oidc-sdk/tree/master/packages/oidc-js#refreshtoken

In addition, the refresh token is automatically refreshed by SDK or when an HTTP request to a protected endpoint fails with a `401` error.

**Comment by samisa-abeysinghe** [comment]
This ticket is pointing to private repos. Do we have publicly accessible samples? 
Also, do we have Ballerina code samples / templates for the same?

**Comment by deshankoswatte** [comment]
> Getting access token: https://github.com/asgardio/asgardio-js-oidc-sdk/tree/master/packages/oidc-js#getaccesstoken
> 
> The token can be refreshed using this: https://github.com/asgardio/asgardio-js-oidc-sdk/tree/master/packages/oidc-js#refreshtoken
> 
> In addition, the refresh token is automatically refreshed by the SDK and when an HTTP request to a protected endpoint fails with a `401` error.

The new links for the above should be as follows.

Get Access Token: https://github.com/asgardeo/asgardeo-auth-js-sdk/tree/master#getAccessToken
Token Refresh: https://github.com/asgardeo/asgardeo-auth-js-sdk/tree/master#refreshAccessToken
